
sonar.host.url=http://localhost:9000
sonar.login=sqp_e51e80b9b6905b4c55646c9697674d49ac31a992

sonar.scanner.forceReloadAll=true
sonar.projectKey=PMS
sonar.projectName=PMS
sonar.sourceEncoding=UTF-8
sonar.sources=src
